import { Country } from '@modules/master/country/entities/country.entity';
import { Province } from '@modules/master/province/entities/province.entity';
import { DataSource } from 'typeorm';

export async function seedProvince(dataSource: DataSource) {
    const arr: Record<string, string[]> = {
        Argentina: [
            'Buenos Aires',
            'Capital Federal',
            'Catamarca',
            'Chaco',
            'Chubut',
            'Cordoba',
            'Corrientes',
            'Entre Rios',
            'Formosa',
            'Jujuy',
            'La Pampa',
            'La Rioja',
            'Mendoza',
            'Misiones',
            'Neuquen',
            'Rio Negro',
            'Salta',
            'San Juan',
            'San Luis',
            'Santa Cruz',
            'Santa Fe',
            'Santiago Del Estero',
            'Tierra De Fuego',
            'Tucuman',
        ],
        Australia: [
            'Aust Capital Terr',
            'New South Wales',
            'Northern Territory',
            'Queensland',
            'South Australia',
            'Tasmania',
            'Victoria',
            'Western Australia',
        ],
        Austria: [
            'Burgenland',
            'Carinthia',
            'Lower Austria',
            'Salzburg',
            'Styria',
            'Tyrol',
            'Upper Austria',
            'Vienna',
            'Vorarlberg',
        ],
        Belgium: [
            'Antwerp',
            'Brabant',
            'Brabant (Walloon)',
            'Brussels (Capital)',
            'Hainaut',
            'Liege',
            'Limburg',
            'Luxembourg',
            'Namur',
            'Oost-Vlaanderen',
            'West-Vlaanderen',
        ],
        'Bonaire, Sint Eustatius and Saba': [
            'Bonaire, Sint Eustatius And Saba',
        ],
        Brazil: [
            'Acre',
            'Alagoas',
            'Amapa',
            'Amazon',
            'Bahia',
            'Brasilia',
            'Ceara',
            'Espirito Santo',
            'Goias',
            'Maranhao',
            'Mato Grosso',
            'Mato Grosso Do Sul',
            'Minas Gerais',
            'Para',
            'Paraiba',
            'Parana',
            'Pernambuco',
            'Piaui',
            'Rio De Janeiro',
            'Rio Grande Do Norte',
            'Rio Grande Do Sul',
            'Rondonia',
            'Roraima',
            'Santa Catarina',
            'Sao Paulo',
            'Sergipe',
            'Tocantins',
        ],
        Bulgaria: [
            'Burgas',
            'Grad Sofiya',
            'Khaskovo',
            'Lovech',
            'Montana',
            'Plovdiv',
            'Ruse',
            'Sofiya',
            'Varna',
        ],
        Cambodia: ['Cambodia'],
        Canada: [
            'Alberta',
            'British Columbia',
            'Manitoba',
            'New Brunswick',
            'Newfoundland & Labr.',
            'Northwest Territory',
            'Nova Scotia',
            'Nunavut',
            'Ontario',
            'Prince Edward Island',
            'Quebec',
            'Saskatchewan',
            'Yukon Territory',
        ],
        Chile: [
            'I - Iquique',
            'Ii - Antofagasta',
            'Iii - Copiapo',
            'Iv - La Serena',
            'Ix - Temuco',
            'Rm - Santiago',
            'V - Valparaiso',
            'Vi - Rancagua',
            'Vii - Talca',
            'Viii - Concepcion',
            'X - Puerto Montt',
            'Xi - Coyhaique',
            'Xii - Punta Arenas',
            'Xiv - Los Rios',
            'Xv - Arica Y Parinac',
        ],
        China: [
            'Anhui',
            'Beijing',
            'Chong Qing',
            'Fujian',
            'Gansu',
            'Guangdong',
            'Guangxi',
            'Guizhou',
            'Hainan',
            'Hebei',
            'Heilongjiang',
            'Henan',
            'Hubei',
            'Hunan',
            'Jiangsu',
            'Jiangxi',
            'Jilin',
            'Liaoning',
            'Nei Mongol',
            'Ningxia',
            'Qinghai',
            'Shaanxi',
            'Shandong',
            'Shanghai',
            'Shanxi',
            'Sichuan',
            'Tianjin',
            'Xinjiang',
            'Xizang',
            'Yunnan',
            'Zhejiang',
        ],
        Colombia: [
            'Amazonas',
            'Antioquia',
            'Arauca',
            'Atlantico',
            'Bogota',
            'Bolivar',
            'Boyaca',
            'Caldas',
            'Caqueta',
            'Casanare',
            'Cauca',
            'Cesar',
            'Choco',
            'Cordoba',
            'Cundinamarca',
            'Guainia',
            'Guaviare',
            'Huila',
            'La Guajira',
            'Magdalena',
            'Meta',
            'Narino',
            'Norte Santander',
            'Putumayo',
            'Quindio',
            'Risaralda',
            'San Andres',
            'Santander',
            'Sucre',
            'Tolima',
            'Valle',
            'Vaupes',
            'Vichada',
        ],
        Croatia: [
            'Bjelovarsko-Bilogors',
            'Dubrovacko-Neretvans',
            'Istarska',
            'Karlovacka',
            'Koprivnicko-Krizevac',
            'Krapinsko-Zagorska',
            'Licko-Senjska',
            'Medjimurska',
            'Osjecko-Baranjska',
            'Pozesko-Slavonska',
            'Rijecko-Goranska',
            'Sibensko-Kninska',
            'Sisacko-Moslavacka',
            'Slavonskobrodska',
            'Splitsko-Dalmatinska',
            'Varazdinska',
            'Viroviticko-Podravac',
            'Vukovarsko-Srijemska',
            'Zadarska',
            'Zagreb',
            'Zagrebacka',
        ],
        Curacao: ['Curacao'],
        Cyprus: ['Nicosia (Lefkosia)'],
        'Czech Republic': [
            'Jihocesky',
            'Jihomoravsky',
            'Karlovarsky',
            'Kralovehradecky',
            'Liberecky',
            'Moravskoslezsky',
            'Olomoucky',
            'Pardubicky',
            'Plzensky',
            'Praha',
            'Stredocesky',
            'Ustecky',
            'Vysocina',
            'Zlinsky',
        ],
        Denmark: [
            'Central Jutland',
            'Danish Capital Reg.',
            'North Jutland',
            'South Denmark',
            'Zealand',
        ],
        'East Timor': ['East Timor'],
        Egypt: [
            'Al Sharqia',
            'Alexandria',
            'Aswan',
            'Asyut',
            'Beheira',
            'Beni Suef',
            'Cairo',
            'Dakahlia',
            'Damietta',
            'Faiyum',
            'Gharbia',
            'Giza',
            'Ismailia',
            'Kafr El-Sheikh',
            'Luxor',
            'Matruh',
            'Minya',
            'Monufia',
            'New Valley',
            'North Sinai',
            'Port Said',
            'Qalyubia',
            'Qena',
            'Red Sea',
            'Sohag',
            'South Sinai',
            'Suez',
        ],
        'European Union': ['European Union'],
        Finland: [
            'Ahvenanmaa',
            'Eastern Finnland',
            'Helsinki',
            'Lappi',
            'Oulu',
            'Southern Finnland',
            'Western Finnland',
        ],
        France: [
            'Ain',
            'Aisne',
            'Allier',
            'Alpes (Hautes)',
            'Alpes (Hte-Provence)',
            'Alpes-Maritimes',
            'Ardeche',
            'Ardennes',
            'Ariege',
            'Aube',
            'Aude',
            'Aveyron',
            'Bas-Rhin',
            'Bouches-Du-Rhone',
            'Calvados',
            'Cantal',
            'Charente',
            'Charente-Maritime',
            'Cher',
            'Correze',
            'Corse-Du-Nord',
            'Corse-Du-Sud',
            "Cote-D'Or",
            "Cotes-D'Armor",
            'Creuse',
            'D.O.M.-T.O.M.',
            'Dordogne',
            'Doubs',
            'Drome',
            'Essonne',
            'Eure',
            'Eure-Et-Loir',
            'Finistere',
            'Gard',
            'Garonne (Haute)',
            'Gers',
            'Gironde',
            'Guadeloupe',
            'Guyane',
            'Haut-Rhin',
            'Hauts-De-Seine',
            'Herault',
            'Hors-France',
            'Ille-Et-Vilaine',
            'Indre',
            'Indre-Et-Loire',
            'Isere',
            'Jura',
            'Landes',
            'Loir-Et-Cher',
            'Loire',
            'Loire (Haute)',
            'Loire-Atlantique',
            'Loiret',
            'Lot',
            'Lot-Et-Garonne',
            'Lozere',
            'Maine-Et-Loire',
            'Manche',
            'Marne',
            'Marne (Haute)',
            'Martinique',
            'Mayenne',
            'Meurthe-Et-Moselle',
            'Meuse',
            'Morbihan',
            'Moselle',
            'Nievre',
            'Nord',
            'Oise',
            'Orne',
            'Paris',
            'Pas-De-Calais',
            'Puy-De-Dome',
            'Pyrenees (Hautes)',
            'Pyrenees-Atlantiques',
            'Pyrenees-Orientales',
            'Reunion',
            'Rhone',
            'Saint Gregoire Cedex',
            'Saint-Pierre-Et-Miq.',
            'Saone (Haute)',
            'Saone-Et-Loire',
            'Sarthe',
            'Savoie',
            'Savoie (Haute)',
            'Seine-Et-Marne',
            'Seine-Maritime',
            'Seine-Saint-Denis',
            'Sevres (Deux)',
            'Somme',
            'Tarn',
            'Tarn-Et-Garonne',
            'Territ.-De-Belfort',
            "Val-D'Oise",
            'Val-De-Marne',
            'Var',
            'Vaucluse',
            'Vendee',
            'Vienne',
            'Vienne (Haute)',
            'Vosges',
            'Wallis-Et-Futuna',
            'Yonne',
            'Yvelines',
        ],
        Germany: [
            'Baden-Wurttemberg',
            'Bavaria',
            'Berlin',
            'Brandenburg',
            'Bremen',
            'Hamburg',
            'Hessen',
            'Lower Saxony',
            'Mecklenburg-Vorpomm.',
            'Nrth Rhine Westfalia',
            'Rhineland Palatinate',
            'Saarland',
            'Saxony',
            'Saxony-Anhalt',
            'Schleswig-Holstein',
            'Thuringia',
        ],
        Greece: [
            'Aitolia Kai Akarnan.',
            'Akhaia',
            'Argolis',
            'Arkadhia',
            'Arta',
            'Attiki',
            'Dhodhekanisos',
            'Dhrama',
            'Evritania',
            'Evros',
            'Evvoia',
            'Florina',
            'Fokis',
            'Fthiotis',
            'Grevena',
            'Ilia',
            'Imathia',
            'Ioannina',
            'Iraklion',
            'Kardhitsa',
            'Kastoria',
            'Kavala',
            'Kefallinia',
            'Kerkira',
            'Khalkidhiki',
            'Khania',
            'Khios',
            'Kikladhes',
            'Kilkis',
            'Korinthia',
            'Kozani',
            'Lakonia',
            'Larisa',
            'Lasithi',
            'Lesvos',
            'Levkas',
            'Magnisia',
            'Messinia',
            'Pella',
            'Pieria',
            'Piraievs',
            'Preveza',
            'Rethimni',
            'Rodhopi',
            'Samos',
            'Serrai',
            'Thesprotia',
            'Thessaloniki',
            'Trikala',
            'Voiotia',
            'Xanthi',
            'Zakinthos',
        ],
        'Hong Kong, SAR China': [
            'Hong Kong Island',
            'Kowloon',
            'New Territories',
        ],
        Hungary: [
            'Bacs-Kiskun',
            'Baranya',
            'Bekes',
            'Bekescsaba',
            'Borsod-Abauj-Zemplen',
            'Budapest',
            'Csongrad',
            'Debrecen',
            'Dunaujvaros',
            'Eger',
            'Fejer',
            'Gyor',
            'Gyor-Moson-Sopron',
            'Hajdu-Bihar',
            'Heves',
            'Hodmezovasarhely',
            'Jasz-Nagykun-Szolnok',
            'Kaposvar',
            'Kecskemet',
            'Komarom-Esztergom',
            'Miskolc',
            'Nagykanizsa',
            'Nograd',
            'Nyiregyhaza',
            'Pecs',
            'Pest',
            'Somogy',
            'Sopron',
            'Szabolcs-Szat.-Bereg',
            'Szeged',
            'Szekesfehervar',
            'Szolnok',
            'Szombathely',
            'Tatabanya',
            'Tolna',
            'Vas',
            'Veszprem',
            'Zala',
            'Zalaegerszeg',
        ],
        India: [
            'Andaman And Nico.Is.',
            'Andhra Pradesh',
            'Arunachal Pradesh',
            'Assam',
            'Bihar',
            'Chandigarh',
            'Chhattisgarh',
            'Dadra And Nagar Hav.',
            'Daman And Diu',
            'Delhi',
            'Goa',
            'Gujarat',
            'Haryana',
            'Himachal Pradesh',
            'Jammu And Kashmir',
            'Jharkhand',
            'Karnataka',
            'Kerala',
            'Lakshadweep',
            'Madhya Pradesh',
            'Maharashtra',
            'Manipur',
            'Meghalaya',
            'Mizoram',
            'Nagaland',
            'Orissa',
            'Puducherry',
            'Punjab',
            'Rajasthan',
            'Sikkim',
            'Tamil Nadu',
            'Tripura',
            'Uttar Pradesh',
            'Uttarakhand',
            'West Bengal',
        ],
        Indonesia: [
            'Aceh',
            'Bali',
            'Banten',
            'Bengkulu',
            'DI Yogyakarta',
            'DKI Jakarta',
            'Gorontalo',
            'Jambi',
            'Jawa Barat',
            'Jawa Tengah',
            'Jawa Timur',
            'Kalimantan Barat',
            'Kalimantan Selatan',
            'Kalimantan Tengah',
            'Kalimantan Timur',
            'Kalimantan Utara',
            'Kep. Bangka Belitung',
            'Kep. Riau',
            'Lampung',
            'Maluku',
            'Maluku Utara',
            'Nusa Tenggara Barat',
            'Nusa Tenggara Timur',
            'Papua',
            'Papua Barat',
            'Riau',
            'Sulawesi Barat',
            'Sulawesi Selatan',
            'Sulawesi Tengah',
            'Sulawesi Tenggara',
            'Sulawesi Utara',
            'Sumatera Barat',
            'Sumatera Selatan',
            'Sumatera Utara',
        ],
        Ireland: [
            'Carlow',
            'Cavan',
            'Clare',
            'Cork',
            'Donegal',
            'Dublin',
            'Galway',
            'Kerry',
            'Kildare',
            'Kilkenny',
            'Laois',
            'Leitrim',
            'Limerick',
            'Longford',
            'Louth',
            'Mayo',
            'Meath',
            'Monaghan',
            'Offaly',
            'Roscommon',
            'Sligo',
            'Tipperary',
            'Waterford',
            'Westmeath',
            'Wexford',
            'Wicklow',
        ],
        Israel: [
            'Central',
            'Haifa',
            'Jerusalem',
            'Northern',
            'Southern',
            'Tel Aviv',
        ],
        Italy: [
            'Agriento',
            'Alessandria',
            'Ancona',
            'Aosta',
            'Arezzo',
            'Ascoli Piceno',
            'Asti',
            'Avellino',
            'Bari',
            'Barletta Andria Tran',
            'Belluno',
            'Benevento',
            'Bergamo',
            'Biella',
            'Bologna',
            'Bolzano',
            'Brescia',
            'Brindisi',
            'Cagliari',
            'Caltanisetta',
            'Campobasso',
            'Carbonia-Iglesias',
            'Caserta',
            'Catania',
            'Catanzaro',
            'Chieti',
            'Como',
            'Cosenza',
            'Cremona',
            'Crotone',
            'Cuneo',
            'Enna',
            'Fermo',
            'Ferrara',
            'Fiume',
            'Florence',
            'Foggia',
            'Forli/Cesana',
            'Frosinone',
            'Genova',
            'Gorizia',
            'Grosseto',
            'Imperia',
            'Isernia',
            "L'Aquila",
            'La Spezia',
            'Latina',
            'Lecce',
            'Lecco',
            'Livorno',
            'Lodi',
            'Lucca',
            'Macerata',
            'Mantova',
            'Massa Carrara',
            'Matera',
            'Medio Campidano',
            'Messina',
            'Milan',
            'Modena',
            'Monza E Brianza',
            'Naples',
            'Novara',
            'Nuoro',
            'Ogliastra',
            'Olbia-Tempio',
            'Oristano',
            'Padova',
            'Palermo',
            'Parma',
            'Pavia',
            'Perugia',
            'Pesaro-Urbino',
            'Pescara',
            'Piacenza',
            'Pisa',
            'Pistoia',
            'Pola',
            'Pordenone',
            'Potenza',
            'Prato',
            'Ragusa',
            'Ravenna',
            'Reggio Calabria',
            'Reggio Emilia',
            'Rieti',
            'Rimini',
            'Rome',
            'Rovigo',
            'Salerno',
            'Sassari',
            'Savona',
            'Siena',
            'Siracusa',
            'Sondrio',
            'Stati Esteri',
            'Taranto',
            'Teramo',
            'Terni',
            'Trapani',
            'Trento',
            'Treviso',
            'Trieste',
            'Turin',
            'Udine',
            'Varese',
            'Venice',
            'Verbania',
            'Vercelli',
            'Verona',
            'Vibo Valentia',
            'Vicenza',
            'Viterbo',
            'Zara',
        ],
        Japan: [
            'Aichi',
            'Akita',
            'Aomori',
            'Chiba',
            'Ehime',
            'Fukui',
            'Fukuoka',
            'Fukushima',
            'Gifu',
            'Gunma',
            'Hiroshima',
            'Hokkaido',
            'Hyogo',
            'Ibaraki',
            'Ishikawa',
            'Iwate',
            'Kagawa',
            'Kagoshima',
            'Kanagawa',
            'Kochi',
            'Kumamoto',
            'Kyoto',
            'Mie',
            'Miyagi',
            'Miyazaki',
            'Nagano',
            'Nagasaki',
            'Nara',
            'Niigata',
            'Oita',
            'Okayama',
            'Okinawa',
            'Osaka',
            'Saga',
            'Saitama',
            'Shiga',
            'Shimane',
            'Shizuoka',
            'Tochigi',
            'Tokushima',
            'Tokyo',
            'Tottori',
            'Toyama',
            'Wakayama',
            'Yamagata',
            'Yamaguchi',
            'Yamanashi',
        ],
        Kazakhstan: [
            'Akmolinskaia',
            'Aktubinskaia',
            'Almatynskaia',
            'Atyrauskaia',
            'Gambilskaia',
            'Karagandinskaia',
            'Kostanaiskaia',
            'Kyzilordinskaia',
            'Mangystayskaia',
            'Pavlodarskaia',
            'Severo-Kazakhstansk',
            'Vostochno-Kazakhstan',
            'Zapadno-Kazakhst',
        ],
        'Korea (South)': [
            'Busan',
            'Chungcheong Buk Do',
            'Chungcheong Nam Do',
            'Daegu',
            'Daejeon',
            'Gangwon Do',
            'Gwangju',
            'Gyeonggi Do',
            'Gyeongsang Buk Do',
            'Gyeongsang Nam Do',
            'Incheon',
            'Jeju',
            'Jeolla Buk Do',
            'Jeolla Nam Do',
            'Sejong',
            'Seoul',
            'Ulsan',
        ],
        Kuwait: ['Kuwait City'],
        Luxembourg: ['Luxembourg'],
        Malaysia: [
            'Johor',
            'Kedah',
            'Kelantan',
            'Kuala Lumpur',
            'Labuan',
            'Melaka',
            'Negeri Sembilan',
            'Pahang',
            'Perak',
            'Perlis',
            'Pulau Pinang',
            'Sabah',
            'Sarawak',
            'Selangor',
            'Trengganu',
            'W.P Putrajaya',
            'Wil. Persekutuan',
        ],
        Mexico: [
            'Aguascalientes',
            'Baja California',
            'Baja California S',
            'Campeche',
            'Chiapas',
            'Chihuahua',
            'Coahuila',
            'Colima',
            'Distrito Federal',
            'Durango',
            'Estado De Mexico',
            'Guanajuato',
            'Guerrero',
            'Hidalgo',
            'Jalisco',
            'Michoacan',
            'Morelos',
            'Nayarit',
            'Nuevo Leon',
            'Oaxaca',
            'Puebla',
            'Queretaro',
            'Quintana Roo',
            'San Luis Potosi',
            'Sinaloa',
            'Sonora',
            'Tabasco',
            'Tamaulipas',
            'Tlaxcala',
            'Veracruz',
            'Yucatan',
            'Zacatecas',
        ],
        NATO: ['Nato'],
        Netherlands: [
            'Drenthe',
            'Flevoland',
            'Friesland',
            'Gelderland',
            'Groningen',
            'Limburg',
            'Noord-Brabant',
            'Noord-Holland',
            'Overijssel',
            'Utrecht',
            'Zeeland',
            'Zuid-Holland',
        ],
        'New Zealand': [
            'Auckland',
            'Bay Of Plenty',
            'Canterbury',
            'Hawke´S Bay',
            'Manawatu-Wanganui',
            'Northland',
            'Otago',
            'Southland',
            'Taranaki',
            'Waikato',
            'Wellington',
            'West Coast',
        ],
        Norway: [
            'Akershus County',
            'Aust-Agder County',
            'Buskerud County',
            'Finnmark County',
            'Hedmark County',
            'Hordaland County',
            'More Og Romsdal C.',
            'Nord-Trondelag Cnty',
            'Nordland County',
            'Oppland County',
            'Oslo',
            'Ostfold County',
            'Rogaland County',
            'Sogn Og Fjordane C.',
            'Sor-Trondelag County',
            'Telemark County',
            'Troms County',
            'Vest-Agder County',
            'Vestfold County',
        ],
        Orange: ['Orange'],
        Peru: [
            'Amazon',
            'Ancash',
            'Apurimac',
            'Arequipa',
            'Ayacucho',
            'Cajamarca',
            'Cuzco',
            'Huancavelica',
            'Huanuco',
            'Ica',
            'Junin',
            'La Libertad',
            'Lambayeque',
            'Lima Y Callao',
            'Loreto',
            'Madre De Dios',
            'Moquegua',
            'Pasco',
            'Piura',
            'Puno',
            'San Martin',
            'Tacna',
            'Tumbes',
            'Ucayali',
        ],
        Philippines: [
            'Bicol',
            'Cagayan Valley',
            'Central Luzon',
            'Central Mindanao',
            'Central Visayas',
            'Eastern Visayas',
            'Ilocos',
            'Northern Mindanao',
            'South Luzon',
            'South Mindanao',
            'West Visayas',
            'Western Mindanao',
        ],
        Poland: [
            'Dolnoslaskie',
            'Kujawsko-Pomorskie',
            'Lodzkie',
            'Lubelskie',
            'Lubuskie',
            'Malopolskie',
            'Mazowieckie',
            'Opolskie',
            'Podkarpackie',
            'Podlaskie',
            'Pomorskie',
            'Slaskie',
            'Swietokrzyskie',
            'Warminsko-Mazurskie',
            'Wielkopolskie',
            'Zachodniopomorskie',
        ],
        Portugal: [
            'Alentejo Central',
            'Alentejo Litoral',
            'Algarve',
            'Alto Alentejo',
            'Alto Tras-Os-Montes',
            'Ave',
            'Baixo Alentejo',
            'Baixo Mondego',
            'Baixo Vouga',
            'Beira Interior Norte',
            'Beira Interior Sul',
            'Cavado',
            'Cova Da Beira',
            'Dao-Lafoes',
            'Douro',
            'Entre Douro E Vouga',
            'Grande Lisboa',
            'Grande Porto',
            'Leziria Do Tejo',
            'Medio Tejo',
            'Minho-Lima',
            'Oeste',
            'Peninsula De Setubal',
            'Pinhal Interior N.',
            'Pinhal Interior Sul',
            'Pinhal Litoral',
            'Reg. Aut. Da Madeira',
            'Reg. Aut. Dos A¿¿Ores',
            'Serra Da Estrela',
            'Tamega',
        ],
        Qatar: ['Doha', 'The North', 'The South', 'The West Coast'],
        Romania: [
            'Alba',
            'Arad',
            'Arges',
            'Bacau',
            'Bihor',
            'Bistrita-Nasaud',
            'Botosani',
            'Braila',
            'Brasov',
            'Bucuresti',
            'Buzau',
            'Calarasi',
            'Caras-Severin',
            'Cluj',
            'Constanta',
            'Covasna',
            'Dimbovita',
            'Dolj',
            'Galati',
            'Giurgiu',
            'Gorj',
            'Harghita',
            'Hunedoara',
            'Ialomita',
            'Iasi',
            'Ilfov',
            'Maramures',
            'Mehedinti',
            'Mures',
            'Neamt',
            'Olt',
            'Prahova',
            'Salaj',
            'Satu Mare',
            'Sibiu',
            'Suceava',
            'Teleorman',
            'Timis',
            'Tulcea',
            'Vaslui',
            'Vilcea',
            'Vrancea',
        ],
        'Russian Federation': [
            'Adigeja Republic',
            'Aginsk Buryat Aut.Di',
            'Altay Territory',
            'Buryat Republic',
            'C.Moscow',
            'C.St-Peterburg',
            'Chakassky Republic',
            'Chanti-Mansyjsky Aut',
            'Chechenskaya Republ.',
            'Chukotka Auton. Dist',
            'Chuvash Republic',
            'Dagestan Republic',
            'Evensky Auton.Distri',
            'Highlands-Altay Rep.',
            'Ingushetija Republic',
            'Jamalo-Nenekchky Aut',
            'Kabardino-Balkar.Rep',
            'Kalmyk Republic',
            'Kamchatka Territory',
            'Karach.-Cherkessk Re',
            'Karelian Republic',
            'Khabarovsk Territory',
            'Komi Republic',
            'Komy Permjats.Aut.Di',
            'Korjacs Auton.Distri',
            'Krasnodar Territory',
            'Krasnoyarsk Territor',
            'Marijskaya Republic',
            'Mordovian Republic',
            'Nenekchky Auton.Dist',
            'North-Osetiya Republ',
            'Perm Territory',
            'Primorye Territory',
            'Republ.Of Bashkortos',
            'Stavropol Territory',
            'Tatarstan Republic',
            'The Amur Area',
            'The Arkhangelsk Area',
            'The Astrakhan Area',
            'The Belgorod Area',
            'The Bryansk Area',
            'The Chelyabinsk Area',
            'The Irkutsk Area',
            'The Ivanovo Area',
            'The Jewish Auton.Are',
            'The Kaliningrad Area',
            'The Kaluga Area',
            'The Kemerovo Area',
            'The Kirov Area',
            'The Kostroma Area',
            'The Kurgan Area',
            'The Kursk Area',
            'The Leningrad Area',
            'The Lipetsk Area',
            'The Magadan Area',
            'The Moscow Area',
            'The Murmansk Area',
            'The Nizhniy Novgorod',
            'The Novgorod Area',
            'The Novosibirsk Area',
            'The Omsk Area',
            'The Orenburg Area',
            'The Oryol Area',
            'The Penza Area',
            'The Pskov Area',
            'The Rostov Area',
            'The Ryazan Area',
            'The Sakhalin Area',
            'The Samara Area',
            'The Saratov Area',
            'The Smolensk Area',
            'The Sverdlovsk Area',
            'The Tambov Area',
            'The Taymir Auton.Dis',
            'The Tomsk Area',
            'The Tula Area',
            'The Tver Area',
            'The Tyumen Area',
            'The Udmurt Republic',
            'The Ulyanovsk Area',
            'The Vladimir Area',
            'The Volgograd Area',
            'The Vologda Area',
            'The Voronezh Area',
            'The Yaroslavl Area',
            'Tuva Republic',
            'Ust-Ordinsky Buryat',
            'Yakutiya-Saha Rrepub',
            'Zabaykalsk Territory',
        ],
        'Serbia and Montenegro': ['Serbia And Montenegro'],
        Singapore: ['Singapore'],
        'Sint Maarten (Dutch part)': ['Sint Maarten (Dutch Part)'],
        Slovakia: [
            'Bratislava',
            'Stredoslovensky',
            'Vychodoslovensky',
            'Zapadoslovensky',
        ],
        Slovenia: [
            'Ajdovscina',
            'Ajdov¹Èina',
            'Beltinci',
            'Benedikt',
            'Bistrica Ob Sotli',
            'Bled',
            'Bloke',
            'Bohinj',
            'Borovnica',
            'Bovec',
            'Braslovèe',
            'Brda',
            'Brezice',
            'Brezovica',
            'Bre¾Ice',
            'Cankova',
            'Celje',
            'Cerklje Na Gorenjske',
            'Cerknica',
            'Cerkno',
            'Cerkvenjak',
            'Crnomelj',
            'Destrnik',
            'Divaèa',
            'Dobje',
            'Dobrepolje',
            'Dobrna',
            'Dobrova-Polhov Grade',
            'Dobrovnik - Dobronak',
            'Dol Pri Ljubljani',
            'Dolenjske Toplice',
            'Dom¾Ale',
            'Dornava',
            'Dravograd',
            'Duplek',
            'Gorenja Vas-Poljane',
            'Gori¹Nica',
            'Gornja Radgona',
            'Gornji Grad',
            'Gornji Petrovci',
            'Grad',
            'Grosuplje',
            'Hajdina',
            'Hodo¹ - Hodos',
            'Horjul',
            'Hoèe-Slivnica',
            'Hrastnik',
            'Hrastnik Lasko',
            'Hrpelje-Kozina',
            'Idrija',
            'Ig',
            'Ilirska Bistrica',
            'Ivanèna Gorica',
            'Izola',
            'Izola - Isola',
            'Jesenice',
            'Jezersko',
            'Jur¹Inci',
            'Kamnik',
            'Kanal',
            'Kidrièevo',
            'Kobarid',
            'Kobilje',
            'Kocevje',
            'Komen',
            'Komenda',
            'Koper',
            'Koper - Capodistria',
            'Kostel',
            'Kozje',
            'Ko¿¿Evje',
            'Kranj',
            'Kranjska Gora',
            'Kri¾Evci',
            'Krsko',
            'Kr¿¿Ko',
            'Kungota',
            'Kuzma',
            'La¿¿Ko',
            'Lenart',
            'Lendava',
            'Lendava - Lendva',
            'Litija',
            'Ljubljana',
            'Ljubljana-Bezigrad',
            'Ljubljana-Center',
            'Ljubljana-Moste-Polj',
            'Ljubljana-Siska',
            'Ljubljana-Vic-Rudnik',
            'Ljubno',
            'Ljutomer',
            'Logatec',
            'Lovrenc Na Pohorju',
            'Lo¹Ka Dolina',
            'Lo¹Ki Potok',
            'Lukovica',
            'Luèe',
            'Maj¹Perk',
            'Maribor',
            'Markovci',
            'Medvode',
            'Menge¹',
            'Metlika',
            'Me¾Ica',
            'Miklav¾ Na Dravskem',
            'Miren-Kostanjevica',
            'Mirna Peè',
            'Mislinja',
            'Moravske Toplice',
            'Moravèe',
            'Mozirje',
            'Murska Sobota',
            'Muta',
            'Naklo',
            'Nazarje',
            'Nova Gorica',
            'Novo Mesto',
            'Odranci',
            'Oplotnica',
            'Ormoz',
            'Ormo¾',
            'Osilnica',
            'Pesnica',
            'Piran',
            'Piran - Pirano',
            'Pivka',
            'Podlehnik',
            'Podvelka',
            'Podèetrtek',
            'Polzela',
            'Postojna',
            'Prebold',
            'Preddvor',
            'Prevalje',
            'Ptuj',
            'Puconci',
            'Radenci',
            'Radeèe',
            'Radlje Ob Dravi',
            'Radovljica',
            'Ravne Na Koroskem',
            'Ravne Na Koro¹Kem',
            'Razkri¾Je',
            'Raèe-Fram',
            'Ribnica',
            'Ribnica Na Pohorju',
            'Rogatec',
            'Roga¹Ka Slatina',
            'Roga¹Ovci',
            'Ruse',
            'Ru¹E',
            'Selnica Ob Dravi',
            'Semiè',
            'Sentjur Pri Celju',
            'Sevnica',
            'Sezana',
            'Se¾Ana',
            'Skofja Loka',
            'Slovenj Gradec',
            'Slovenska Bistrica',
            'Slovenske Konjice',
            'Smarje Pri Jelsah',
            'Sodra¾Ica',
            'Solèava',
            'Star¹E',
            'Sveta Ana',
            'Sveti Andra¾ V Slov.',
            'Sveti Jurij',
            'Tabor',
            'Ti¹Ina',
            'Tolmin',
            'Trbovlje',
            'Trebnje',
            'Trnovska Vas',
            'Trzic',
            'Trzin',
            'Tr¾Iè',
            'Turni¹Èe',
            'Velenje',
            'Velika Polana',
            'Velike La¹Èe',
            'Ver¾Ej',
            'Videm',
            'Vipava',
            'Vitanje',
            'Vodice',
            'Vojnik',
            'Vransko',
            'Vrhnika',
            'Vuzenica',
            'Zagorje Ob Savi',
            'Zalec',
            'Zavrè',
            'Zreèe',
            '©Alovci',
            '©Empeter - Vrtojba',
            '©Entilj',
            '©Entjernej',
            '©Entjur Pri Celju',
            '©Enèur',
            '©Kocjan',
            '©Kofja Loka',
            '©Kofljica',
            '©Marje Pri Jel¹Ah',
            '©Martno Ob Paki',
            '©O¹Tanj',
            '©Tore',
            '®Alec',
            '®Elezniki',
            '®Etale',
            '®Iri',
            '®U¾Emberk',
            '¿¿Irovnica',
            'Èren¹Ovci',
            'Èrna Na Koro¹Kem',
            'Èrnomelj',
        ],
        'South Africa': [
            'Eastern Cape',
            'Free State',
            'Gauteng',
            'Kwazulu-Natal',
            'Limpopo',
            'Mpumalanga',
            'Northern Cape',
            'Northwest',
            'Western Cape',
        ],
        Spain: [
            'Alava',
            'Albacete',
            'Alicante',
            'Almeria',
            'Asturias',
            'Avila',
            'Badajoz',
            'Baleares',
            'Barcelona',
            'Burgos',
            'Caceres',
            'Cadiz',
            'Cantabria',
            'Castellon',
            'Ciudad Real',
            'Cordoba',
            'Cuenca',
            'Gerona',
            'Granada',
            'Guadalajara',
            'Guipuzcoa',
            'Huelva',
            'Huesca',
            'Jaen',
            'La Coruna',
            'La Rioja',
            'Las Palmas',
            'Leon',
            'Lerida',
            'Lugo',
            'Madrid',
            'Malaga',
            'Murcia',
            'Navarra',
            'Orense',
            'Palencia',
            'Pontevedra',
            'Salamanca',
            'Segovia',
            'Sevilla',
            'Soria',
            'Sta. Cruz Tenerife',
            'Tarragona',
            'Teruel',
            'Toledo',
            'Valencia',
            'Valladolid',
            'Vizcaya',
            'Zamora',
            'Zaragoza',
        ],
        Sweden: [
            'Blekinge County',
            'Dalarnas County',
            'Gaevleborg County',
            'Gotland County',
            'Halland County',
            'Jaemtland County',
            'Joenkoeping County',
            'Kalmar County',
            'Kronoberg County',
            'Norrbotten County',
            'Oerebro County',
            'Oestergoetland Cnty',
            'Skaane County',
            'Soedermanland County',
            'Stockholm County',
            'Uppsala County',
            'Vaermland County',
            'Vaesterbotten County',
            'Vaesternorrland Cnty',
            'Vaestmanland County',
            'Vaestra Goetaland C.',
        ],
        Switzerland: [
            'Aargau',
            'Ausser-Rhoden',
            'Basel Land',
            'Basel Stadt',
            'Bern',
            'Fribourg',
            'Geneva',
            'Glarus',
            'Graubuenden',
            'Inner-Rhoden',
            'Jura',
            'Lucerne',
            'Neuchatel',
            'Nidwalden',
            'Obwalden',
            'Schaffhausen',
            'Schwyz',
            'Solothurn',
            'St. Gallen',
            'Thurgau',
            'Ticino',
            'Uri',
            'Valais',
            'Vaud',
            'Zug',
            'Zurich',
        ],
        'Taiwan, Republic of China': [
            'Fu-Chien',
            'Kao-Hsiung',
            'Taipei',
            'Taiwan',
            'T´Ai-Pei',
        ],
        Thailand: [
            'Amnat Charoen',
            'Ang Thong',
            'Bueng Kan',
            'Buriram',
            'Chachoengsao',
            'Chai Nat',
            'Chaiyaphum',
            'Chanthaburi',
            'Chiang Mai',
            'Chiang Rai',
            'Chon Buri',
            'Chumphon',
            'Kalasin',
            'Kamphaeng Phet',
            'Kanchanaburi',
            'Khon Kaen',
            'Krabi',
            'Krung Thep',
            'Lampang',
            'Lamphun',
            'Loei',
            'Lop Buri',
            'Mae Hong Son',
            'Maha Sarakham',
            'Mahanakhon',
            'Mukdahan',
            'Nakhon Nayok',
            'Nakhon Pathom',
            'Nakhon Phanom',
            'Nakhon Ratchasima',
            'Nakhon Sawan',
            'Nakhon Si Thammarat',
            'Nan',
            'Narathiwat',
            'Nong Bua Lamphu',
            'Nong Khai',
            'Nonthaburi',
            'Pathum Thani',
            'Pattani',
            'Phangnga',
            'Phatthalung',
            'Phayao',
            'Phetchabun',
            'Phetchaburi',
            'Phichit',
            'Phitsanulok',
            'Phra Nakhon Si Ayut.',
            'Phrae',
            'Phuket',
            'Prachin Buri',
        ],
        Turkey: [
            'Adana',
            'Adiyaman',
            'Afyon',
            'Agri',
            'Aksaray',
            'Amasya',
            'Ankara',
            'Antalya',
            'Ardahan',
            'Artvin',
            'Aydin',
            'Balikesir',
            'Bartin',
            'Batman',
            'Bayburt',
            'Bilecik',
            'Bingöl',
            'Bitlis',
            'Bolu',
            'Burdur',
            'Bursa',
            'Canakkale',
            'Cankiri',
            'Corum',
            'Denizli',
            'Diyarbakir',
            'Edirne',
            'Elazig',
            'Erzincan',
            'Erzurum',
            'Eskisehir',
            'Gaziantep',
            'Giresun',
            'Guemueshane',
            'Hakkari',
            'Hatay',
            'Icel',
            'Igdir',
            'Isparta',
            'Istanbul',
            'Izmir',
            'K.Marash',
            'Karaman',
            'Kars',
            'Kastamonu',
            'Kayseri',
            'Kirikkale',
            'Kirklareli',
            'Kirshehir',
            'Kocaeli',
            'Konya',
            'Kuetahya',
            'Malatya',
            'Manisa',
            'Mardin',
            'Mugla',
            'Mush',
            'Nevshehir',
            'Nigde',
            'Ordu',
            'Rize',
            'Sakarya',
            'Samsun',
            'Shanliurfa',
            'Shirnak',
            'Siirt',
            'Sinop',
            'Sivas',
            'Tekirdag',
            'Tokat',
            'Trabzon',
            'Tunceli',
            'Ushak',
            'Van',
            'Yalova',
            'Yozgat',
            'Zonguldak',
        ],
        Ukraine: [
            "Cherkas'Ka",
            "Chernigivs'Ka",
            "Chernovits'Ka",
            "Dnipropetrovs'Ka",
            "Donets'Ka",
            "Harkivs'Ka",
            "Hersons'Ka",
            "Hmel'Nits'Ka",
            "Ivano-Frankivs'Ka",
            "Kievs'Ka",
            "Kirovograds'Ka",
            "L'Vivsbka",
            "Lugans'Ka",
            'M.Kiev',
            "M.Sevastopil'",
            "Mikolaivs'Ka",
            "Odes'Ka",
            "Poltavs'Ka",
            'Respublika Krim',
            "Rivnens'Ka",
            "Sums'Ka",
            "Ternopil'S'Ka",
            "Vinnits'Ka",
            "Volins'Ka",
            "Zakarpats'Ka",
            "Zaporiz'Ka",
            "Zhitomirs'Ka",
        ],
        'United Arab Emirates': ['Dubai'],
        'United Kingdom': [
            'Aberdeenshire',
            'All',
            'Anglesey',
            'Angus/Forfarshire',
            'Antrim',
            'Argyllshire',
            'Armagh',
            'Ayrshire',
            'Banffshire',
            'Bath&Nthestsomerset',
            'Bedfordshire',
            'Berkshire',
            'Berwickshire',
            'Brecknockshire',
            'Buckinghamshire',
            'Buteshire',
            'Caernarfonshire',
            'Caithness',
            'Cambridgeshire',
            'Cardiganshire',
            'Carmarthenshire',
            'Cheshire',
            'Clackmannanshire',
            'Cornwall',
            'Cromartyshire',
            'Cumberland',
            'Denbighshire',
            'Derbyshire',
            'Devon',
            'Dorset',
            'Down',
            'Dumfriesshire',
            'Dunbartonshire',
            'Durham',
            'East Lothian',
            'East Sussex',
            'Essex',
            'Fermanagh',
            'Fife',
            'Flintshire',
            'Gloucestershire',
            'Hampshire',
            'Hereford And Worcs.',
            'Hertfordshire',
            'Huntingdonshire',
            'Invernesshire',
            'Isle Of Wight',
            'Kent',
            'Kincardineshire',
            'Kinross-Shire',
            'Kirkcudbrightshire',
            'Lanarkshire',
            'Lancashire',
            'Leicestershire',
            'Lincolnshire',
            'Londonderry',
            'Merioneth',
            'Mid Glamorgan',
            'Middlesex',
            'Midlothian',
            'Monmouthshire',
            'Montgomeryshire',
            'Morayshire',
            'Nairnshire',
            'Norfolk',
            'North Yorkshire',
            'Northamptonshire',
            'Northumberland',
            'Nottinghamshire',
            'Orkney',
            'Oxfordshire',
            'Peeblesshire',
            'Pembrokeshire',
            'Perthshire',
            'Radnorshire',
            'Renfrewshire',
            'Ross-Shire',
            'Roxburghshire',
            'Rutland',
            'Selkirkshire',
            'Shetland',
            'Shropshire',
            'Somerset',
            'South Glamorgan',
            'South Yorkshire',
            'Staffordshire',
            'Stirlingshire',
            'Suffolk',
            'Surrey',
            'Sutherland',
            'Tyrone',
            'Warwickshire',
            'West Glamorgan',
            'West Lothian',
            'West Sussex',
            'West Yorkshire',
            'Westmorland',
            'Wigtownshire',
            'Wiltshire',
            'Worcestershire',
        ],
        'United Nations': ['United Nations'],
        'United States of America': [
            'Alabama',
            'Alaska',
            'American Samoa',
            'Arizona',
            'Arkansas',
            'California',
            'Colorado',
            'Connecticut',
            'Delaware',
            'District Of Columbia',
            'Florida',
            'Georgia',
            'Guam',
            'Hawaii',
            'Idaho',
            'Illinois',
            'Indiana',
            'Iowa',
            'Kansas',
            'Kentucky',
            'Louisiana',
            'Maine',
            'Maryland',
            'Massachusetts',
            'Michigan',
            'Minnesota',
            'Mississippi',
            'Missouri',
            'Montana',
            'Nebraska',
            'Nevada',
            'New Hampshire',
            'New Jersey',
            'New Mexico',
            'New York',
            'North Carolina',
            'North Dakota',
            'Northern Mariana Isl',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Pennsylvania',
            'Puerto Rico',
            'Rhode Island',
            'South Carolina',
            'South Dakota',
            'Tennessee',
            'Texas',
            'Utah',
            'Vermont',
            'Virgin Islands',
            'Virginia',
            'Washington',
            'West Virginia',
            'Wisconsin',
            'Wyoming',
        ],
        'Venezuela (Bolivarian Republic)': [
            'Amazon',
            'Anzoategui',
            'Apure',
            'Aragua',
            'Barinas',
            'Bolivar',
            'Carabobo',
            'Cojedes',
            'Delta Amacuro',
            'Distrito Federal',
            'Falcon',
            'Guarico',
            'Lara',
            'Merida',
            'Miranda',
            'Monagas',
            'Nueva Esparta',
            'Portuguesa',
            'Sucre',
            'Tachira',
            'Trujillo',
            'Vargas',
            'Yaracuy',
            'Zulia',
        ],
    };

    const provinceRepo = dataSource.getRepository(Province);
    const countryRepo = dataSource.getRepository(Country);

    for (const [countryName, data] of Object.entries(arr)) {
        const country = await countryRepo.findOne({
            where: { name: countryName },
        });

        if (!country) {
            console.warn(`country ${countryName} does not exists`);
            continue;
        }

        for (const obj of data) {
            await provinceRepo.save(
                provinceRepo.create({
                    name: obj,
                    country: {
                        id: country.id,
                    },
                }),
            );
        }

        console.log(`✅ Seeded ${countryName} (${data.length} provinces)`);
    }

    console.log('✅ Province seeded');
}
