export enum VendorStatusEnum {
  PRE_REGISTRATION = 'PRE_REGISTRATION',
  WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL',
  ACTIVE = 'ACTIVE',
  REVISION = 'REVISION',
  INACTIVE = 'INACTIVE',
  BLACKLISTED = 'BLACKLISTED',
  REJECTED = 'REJECTED'
}

export enum VendorStageEnum {
  CANDIDATE = 'CANDIDATE',
  VENDOR = 'VENDOR'
}

export enum VendorTypeEnum {
  LOCAL = 'LOCAL',
  FOREIGN = 'FOREIGN',
  INDIVIDUAL = 'INDIVIDUAL'
}
