export enum WorkflowCode {
    VENDOR_REGISTRATION = 'WF_CALON_VENDOR',
    VENDOR_UPDATE = 'WF_UBAH_VENDOR',
    DIGITAL_SIGNATURE = 'WF_TTD',
    PROPOSED_TO_REJECT = 'WF_PTR',
    DELETE_COMPANY_ACCOUNT = 'WF_DCA',
    REACTIVATION = 'WF_REAKTIVASI',
    BLACKLIST_UNBLACKLIST = 'WF_BLACKLIST',
    ROLE_EXPIRED = 'WF_ROLE_EXPIRED'
}

export enum WorkflowStepCode {
    ADMIN_OPS = 'ADMIN_OPS',
    APPROVER_1 = 'APPROVER_1',
    APPROVER_2 = 'APPROVER_2',
}